### ISSUE TITLE
Support for other projections

### ISSUE THREAD

**Issue by PeaceNlove** [Esri/koop#145]
Is it possible to get the data from koop in other projections? I think I heard it was possible to do so at the devsummit, but I'm not sure. Looking at the code, I see a lot of hardcoded 4326.

**Comment by chelm** [comment]
@PeaceNlove Currently yes there are a lot of hardcoded 4326 since koop normalizing all data to geographic. It's currently only possible to get projected data in Shapefiles, but this will change in the future. 

To download a shapefile in a different projection the koop `Exporter` can take in a projection as either WKT proj string or an Esri proj code. But at this time it will only reproject shp exports. In the future koop will support the feature service `outSR` params that will do the re-projection for feature services across any koop provider. 

Make sense?

**Comment by PeaceNlove** [comment]
thanks for the quick response :-)
I tried the following url:
http://localhost:1337/agol/rug/565fa711b52c4726b3ddc585ed57b935/0.zip?wkid=28992

and I figured out i could debug using: node debug server.js and adding debugger; where I want my breakpoints. As far as I could figure out, the wkid is put as integer 28992 into the options object at line 470 of koop-agol\controller\index.js, but this wkid property is not used as far as I can see in de koop\lib\exporter.js and the exported shapefile is still in 4326. 

Do you have a suggestion for what I should do to get this working?

**Comment by chelm** [comment]
@PeaceNlove We'll need to add the ability to have the query string param override the wkid in the service. Can you send me the link to the feature service so I can test this?

**Comment by PeaceNlove** [comment]
My feature service is https://geo.rug.nl/arcgis/rest/services/Administratief/Gemeente_2015/MapServer and it is available in AGOL at http://rug.maps.arcgis.com/home/item.html?id=565fa711b52c4726b3ddc585ed57b935

**Comment by chelm** [comment]
@PeaceNlove I have made a change to the koop-agol provider (the only one that supports auto-passing the wkid param to the exporter methods) that will use a given wkid (as ?wkid=28992) from the query string over that which is supplied by the service.

If you install the latest koop-agol provider (via npm install) you'll see the url you posted here https://github.com/Esri/koop/issues/145#issuecomment-91330335 work. 

Let me know of any issues you run into.
