### ISSUE TITLE
zero config

### ISSUE THREAD

**Issue by ngoldman** [Esri/koop#186]
Koop should be able to run with zero configuration. This means passing nothing when calling the constructor, e.g.

```
var app = require('express')()
var koop = require('koop')()
app.use(koop)
app.listen(1337)
```

I made a repo to demonstrate the problem: https://github.com/ngoldman/koop-zero

I don't think this should cause an error that kills the server. My suggestion is that it should just run the server, log a message saying Koop is running but no cache or providers have been configured, and provide a link on how to configure them.

@chelm @dmfenton @jgravois if this makes sense I can work on this feature and add it into the next release. If this isn't the right course of action, I still think a more informative error message is needed.

**Comment by chelm** [comment]
I support it. Let me know if I can help in any way

**Comment by jgravois** [comment]
*in LOTR accent*: you have my :hocho:

**Comment by slibby** [comment]
I think https://github.com/koop/koop-sample-app provides a good zero-config starting point, but agree that the error should be worked around. i.e. if there is no config file and no log file, it shouldn't crash out so horridly.

**Comment by chelm** [comment]
so @ngoldman it sounds like the work here is actually to remove the reliance on a config file / object inside koop. Then koop-zero would work fine. 

I still think the config is crucial for doing things in production and even development. Having a persistent cache is so helpful.

**Comment by chelm** [comment]
haha I just realized i made this comment inside the koop repo! So I'll probably get this fixed today and it will be added into the release process.

**Comment by chelm** [comment]
So @jwieringa brings up some changes he wants to make to our deploy process that would stop writing config files all together. Instead it would rely on ENV vars. 

@ngoldman or @JerrySievert what is the best practice in node apps that need things DB connections? Use ENV vars or Config files?

**Comment by ngoldman** [comment]
@chelm Just to clarify I'm not arguing for doing away with config files here, just that Koop should be able to run without one without crashing. If you and @jwieringa think moving away from config files altogether in favor of ENV vars is desirable, that's another matter.

**Comment by ngoldman** [comment]
@chelm to answer your question, I think there's enough configuration necessary between providers, caches, tokens, and other unexpected future configuration that a config object supplied by a file is easier to manage than a large number of namespaced environmental variables.

**Comment by jwieringa** [comment]
Following up on ENVs, both myself and @kpettijohn would like the ability to deploy the application without the dependency upon external libraries and configuration files. I don't intend to say a config file shouldn't be used in some environments or stacks, for example a config file based solution that uses ENVs might look like https://github.com/cmanzana/node-figaro. The value that I'm looking for is to make Koop easier to deploy with different configuration management tools and on multiple operating systems. Someone who has said this better: http://12factor.net/config

That said, I think I've learned that this issue is about something different, so I'll open up a separate issue as I believe moving configs to ENVs will take some thought/discussion.

**Comment by ngoldman** [comment]
@jwieringa++ good reasoning, separate issue. Look forward to the discussion, I think it's worth exploring and fleshing out.
